<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php 
$_lazyHelper    = $this->helper('Magiccart\Alothemes\Helper\Lazyload');
?>
<header class="page-header alothemes">
  <div class="header">
    <div class="header-content menu-mobile header-sticker">
      <div class="header-menu">
        <?php echo $this->getChildHtml('navigation.sections'); ?>
        <?php echo $this->getChildHtml('catalog.topnav'); ?>
      </div>
      <div class="header-logo">
        <?php echo $_lazyHelper->notLazyloadImage($this->getChildHtml('logo')); ?>
      </div>
      <div class="header-content-custom">
        <?php echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('static_header_top')->toHtml();?>
      </div>
      <div class="tool-header">
        <div class="search-area header-search">
          <?php echo $this->getChildHtml('top.search'); ?>
        </div>
        <div class="header-account">
          <div class="toggle-tab">
            <span class="header-icon user"></span>
          </div>
          <div class="toggle-content">
            <?php echo $this->getChildHtml('header.links'); ?>
          </div>
        </div>
        <?php echo $this->getChildHtml('minicart'); ?>
        <div class="header-toggle-menu">
          <span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>
        </div>
      </div>
    </div>
  </div>
</header>