<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-copyright">
	<div class="copyright-content">
		<div class="main1">
			<span class="copyright">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('theme_name')->toHtml(); ?>
				<?php /* @escapeNotVerified */ echo preg_replace('/yyyy/', date('Y'), $block->getCopyright()); ?>
				</span>
		</div>	
		<div class="main2">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-footer-menu')->toHtml(); ?>
		</div>
		<div class="main3">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-social')->toHtml();?>
		</div>
	</div>
	<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Back to Top')?></span></a>
</div>