<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-11-29 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-12-04 11:07:49
 */
?>
<?php
/**
 * Categories block
 *
 * @var $block \Magepow\Categories\Block\Categories
 */

$categories       = $block->getCategories();
$layout           = $block->getLayout();
$heading          = $block->getHeading();
$description      = $block->isShowDescription();

?>
<?php if (empty($categories)) return ?>
<?php $selector = 'alo-content-'.uniqid(); ?>
<div class="magepow-categories <?php echo $selector ?>" >
    <?php if ($heading): ?>
        <h3 class="title"><?php echo $heading ?></h3>
    <?php endif; ?>
    <ul class="categories <?php echo $layout ?>"
        <?php foreach ($this->getFrontendCfg() as $opt) :?>
            data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
        <?php endforeach;?>  
        >
        <?php foreach ($categories as $cat): ?>
            <li class="item">
                <a href="<?php echo $cat->getUrl() ?>">
                    <div class="category-image"><img src="<?php echo $this->getImage($cat) ?>" alt="<?php echo $cat->getName() ?>"/></div>
                    <div class="category-name"><span><?php echo $cat->getName() ?></span></div>
                </a>
                <?php if($description): ?>
                    <div class="category-description">
                        <?php echo $this->getDescription($cat) ?>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>    
</div>

<script type="text/javascript">
    require([
        'jquery',
        'magiccart/slick',
        'alothemes',
        ], function($, slick, alothemes){
            var categories  = $('.<?php echo $selector ?> .categories');
            if(categories.length) $('head').append(magicproduct(categories, '.item'));
    });
</script>
